### PR TITLE
zeroconf v0.100.0

### PR DESCRIPTION
**Pull request by jjerphan**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Should we try to publish older versions or not?

### CODE REVIEW

**Comment by jjerphan** [comment]
@conda-forge-admin, please rerender

**Comment by jjerphan** [comment]
@abloemert: do this looks good to you? Should we try to publish older versions than v0.100.0 or not?

If this gets merged, we can then easily publish all version until the current one. :slightly_smiling_face:

**Comment by jjerphan** [comment]
@abloemert: is it OK for you if I merge PR to publish new versions?

**Comment by jjerphan** [comment]
Due to the small bus factor, I am merging this PR for now and I am taking responsibility if something breaks.

**Comment by abloemert** [comment]
Looks fine for me, thanks!

**Pull request merged**
