### PR TITLE
updated to 0.27.1

### PR DESCRIPTION
**Pull request by nerohmot**
Checklist
* [X] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by nerohmot** [comment]
@conda-forge-admin, please rerender

**Comment by nerohmot** [comment]
@abloemert Hoi Arnold,

Ik denk dat de auto-bot niet (meer) werkt ...
```sh
me@mybox$ conda search zeroconf
Loading channels: done
# Name                       Version           Build  Channel             
zeroconf                      0.20.0            py_0  conda-forge         
zeroconf                      0.21.0            py_0  conda-forge         
zeroconf                      0.21.1            py_0  conda-forge         
zeroconf                      0.21.2            py_0  conda-forge         
zeroconf                      0.21.3            py_0  conda-forge         
zeroconf                      0.22.0            py_0  conda-forge         
zeroconf                      0.23.0            py_0  conda-forge         
zeroconf                      0.24.0            py_0  conda-forge         
zeroconf                      0.24.1            py_0  conda-forge         
zeroconf                      0.24.2            py_0  conda-forge         
zeroconf                      0.24.3            py_0  conda-forge         
zeroconf                      0.24.4            py_0  conda-forge         
zeroconf                      0.24.5            py_0  conda-forge  
```
terwijl ze op pypi.org al aan 27.1 zitten ...
Ik heb dus manueel een 0.27.1 gemaakt :-)

Cioa,

Tom

**Comment by abloemert** [comment]
@conda-forge-admin, please rerender

**Comment by abloemert** [comment]
> Je kan `@conda-forge-admin,please add bot automerge` uitvoeren, waardoor een nieuwe versie automatisch wordt gemergd :-)

Ga ik doen, thanks!

**Comment by abloemert** [comment]
I see that version 0.28.0 needs an update in the requirements section (`ifaddr` has a minimum version from that version), so lets enable automerge after this version

**Pull request merged**
